server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: longchain4j-study
  
  # 日志配置
  logging:
    level:
      com.example.longchain4jstudy: DEBUG
      dev.langchain4j: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Ollama配置
ollama:
  base-url: http://localhost:11434
  model: qwen3:0.6b
  timeout: 60

# 应用信息
info:
  app:
    name: LongChain4j Study
    version: 1.0.0
    description: LongChain4j学习项目 - 集成Ollama聊天示例 